//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: base.proto
namespace higgs_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameMessage")]
  public partial class GameMessage : global::ProtoBuf.IExtensible
  {
    public GameMessage() {}
    
    private byte[] _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLogin")]
  public partial class ReqLogin : global::ProtoBuf.IExtensible
  {
    public ReqLogin() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AckLogin")]
  public partial class AckLogin : global::ProtoBuf.IExtensible
  {
    public AckLogin() {}
    
    private uint _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint success
    {
      get { return _success; }
      set { _success = value; }
    }
    private uint _userid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _nickname;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMatch")]
  public partial class ReqMatch : global::ProtoBuf.IExtensible
  {
    public ReqMatch() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _fight_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fight_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fight_type
    {
      get { return _fight_type; }
      set { _fight_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _nickname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NtfMatch")]
  public partial class NtfMatch : global::ProtoBuf.IExtensible
  {
    public NtfMatch() {}
    
    private readonly global::System.Collections.Generic.List<higgs_message.PlayerInfo> _playerinfoList = new global::System.Collections.Generic.List<higgs_message.PlayerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerinfoList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<higgs_message.PlayerInfo> playerinfoList
    {
      get { return _playerinfoList; }
    }
  
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqSelectHero")]
  public partial class ReqSelectHero : global::ProtoBuf.IExtensible
  {
    public ReqSelectHero() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private uint _heroid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"heroid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint heroid
    {
      get { return _heroid; }
      set { _heroid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerHeroInfo")]
  public partial class PlayerHeroInfo : global::ProtoBuf.IExtensible
  {
    public PlayerHeroInfo() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _heroid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"heroid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint heroid
    {
      get { return _heroid; }
      set { _heroid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NtfSelectHeroFinish")]
  public partial class NtfSelectHeroFinish : global::ProtoBuf.IExtensible
  {
    public NtfSelectHeroFinish() {}
    
    private readonly global::System.Collections.Generic.List<higgs_message.PlayerHeroInfo> _select_herolist = new global::System.Collections.Generic.List<higgs_message.PlayerHeroInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"select_herolist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<higgs_message.PlayerHeroInfo> select_herolist
    {
      get { return _select_herolist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGameStart")]
  public partial class ReqGameStart : global::ProtoBuf.IExtensible
  {
    public ReqGameStart() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqStartMove")]
  public partial class ReqStartMove : global::ProtoBuf.IExtensible
  {
    public ReqStartMove() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqChangeDir")]
  public partial class ReqChangeDir : global::ProtoBuf.IExtensible
  {
    public ReqChangeDir() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private int _angle;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqEndMove")]
  public partial class ReqEndMove : global::ProtoBuf.IExtensible
  {
    public ReqEndMove() {}
    
    private uint _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}